name: Build, Test, and Deploy Unity Project

on: [push, pull_request]

jobs:
  buildWindows:
    name: Build StandaloneWindows64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          # Cache the Library inside the project folder (has a space → quote it)
          path: "QA - Final/Library"
          key: Library-StandaloneWindows64-${{ hashFiles('QA - Final/Assets/**', 'QA - Final/Packages/**', 'QA - Final/ProjectSettings/**') }}
          restore-keys: |
            Library-StandaloneWindows64-
            Library-

      - name: Free disk space (optional)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.43f1
          projectPath: "QA - Final"              # <-- important
          targetPlatform: StandaloneWindows64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64

  runPlaymodeTests:
    name: Run Playmode Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: "QA - Final/Library"
          key: Library-PlaymodeTests-${{ hashFiles('QA - Final/Assets/**', 'QA - Final/Packages/**', 'QA - Final/ProjectSettings/**') }}
          restore-keys: |
            Library-PlaymodeTests-
            Library-

      - name: Run Unity Playmode Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.43f1
          projectPath: "QA - Final"              # <-- important
          testMode: playmode                     # <-- lowercase
          artifactsPath: artifacts/TestResults/Playmode
          # If you *do* want coverage, also add:
          # coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;dontClear

      - name: Upload Playmode Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Playmode-Test-Results
          path: artifacts/TestResults/Playmode

  deployToGitHubReleases:
    name: Deploy to GitHub Releases
    runs-on: ubuntu-latest
    needs: buildWindows
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: ./build/StandaloneWindows64

      - name: Archive Build Folder
        run: tar -czvf build/StandaloneWindows64.tar.gz -C build/ StandaloneWindows64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/StandaloneWindows64.tar.gz
          name: Release ${{ github.ref_name }}
          body: |
            New release based on tag ${{ github.ref_name }}.
            This release includes the StandaloneWindows64 build, compressed for easier download.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
